### PR TITLE
Ver 1.5.2 - updated free.txt as of 2017-11-14

### PR DESCRIPTION
**Pull request by rnemec**
For deployments that cannot run `update`, only have this as dependency, the updated `free.txt` should do it.

### CODE REVIEW

**Comment by chasingSublimity** [comment]
Thanks @rnemec, I'm taking a look. 👍

**Comment by chasingSublimity** [comment]
Just out of curiosity, where did you pull those domains from? :)

**Comment by rnemec** [comment]
Just ran the update script 😄

**Review by chasingSublimity — APPROVED** [review]
LGTM

**Pull request merged**
